# Numpy basics

Importing library and set an alias **np** for it.

In [1]:
import numpy as np

In [47]:
a1 = [1, 2, 3, 4, 5]

np_a1 = np.array(a1)
np_a1b

array([1, 2, 3, 4, 5])

#### Get Type and Data Dimentions

In [44]:
print(np_a1.shape)
print(type(np_a1))

(5,)
<class 'numpy.ndarray'>


#### Appending ELement

In [48]:
a1.append(6)

a2 = [7, 8, 9, 10]

np_a2 = np.array(a1 + a2)
np_a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Two Dimentional Array

In [53]:
a3 = [[1, 2], [3, 4]]

np_a3 = np.array(a3)
np_a3.shape # returns a list in which first value represents no of rows and second value represents no of columns

(2, 2)

#### Specify Datatype at the time of array creation and change it afterwords

In [63]:
a4 = [[1, 2], [3, 4]]

np_a4 = np.array(a4, dtype="float")

print(f'Float: {np_a4[0][0]}')

integer_type = np_a4.astype('int')
string_type = integer_type.astype('str')

print(f'Integer: {integer_type[0][0]}')
print(f'String: {string_type[0][0]}')

Float: 1.0
Integer: 1
String: 1


## nan(Not a Number) & inf (Infinity)

In [75]:
a5 = [[1, np.nan], [2, np.inf]]

np_a5 = np.array(a5)

is_nan_or_inf = np.isnan(np_a5) | np.isinf(np_a5)

print(is_nan_or_inf)

np_a5[is_nan_or_inf] = 0.0

np_a5

[[False  True]
 [False  True]]


array([[1., 0.],
       [2., 0.]])