# Numpy basics

Importing library and set an alias **np** for it.

In [1]:
import numpy as np

In [2]:
a1 = [1, 2, 3, 4, 5]

np_a1 = np.array(a1)
np_a1

array([1, 2, 3, 4, 5])

#### Get Type and Data Dimentions

In [3]:
print(np_a1.shape)
print(type(np_a1))

(5,)
<class 'numpy.ndarray'>


#### Appending ELement

In [4]:
a1.append(6)

a2 = [7, 8, 9, 10]

np_a2 = np.array(a1 + a2)
np_a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Two Dimentional Array

In [5]:
a3 = [[1, 2], [3, 4]]

np_a3 = np.array(a3)
np_a3.shape # returns a list in which first value represents no of rows and second value represents no of columns

(2, 2)

#### Specify Datatype at the time of array creation and change it afterwords

In [6]:
a4 = [[1, 2], [3, 4]]

np_a4 = np.array(a4, dtype="float")

print(f'Float: {np_a4[0][0]}')

integer_type = np_a4.astype('int')
string_type = integer_type.astype('str')

print(f'Integer: {integer_type[0][0]}')
print(f'String: {string_type[0][0]}')

Float: 1.0
Integer: 1
String: 1


## nan(Not a Number) & inf (Infinity)

In [7]:
a5 = [[1, np.nan], [2, np.inf]]

np_a5 = np.array(a5)

is_nan_or_inf = np.isnan(np_a5) | np.isinf(np_a5)

print(is_nan_or_inf)

np_a5[is_nan_or_inf] = 0.0

np_a5

[[False  True]
 [False  True]]


array([[1., 0.],
       [2., 0.]])

### Basic Statistic Operations

In [8]:
# Mean, Median, Standard diviation, varience

np_a5.mean()
np.median(np_a5)
np_a5.std()
np_a5.var()

0.6875

## ravel, flatten, reshape

In [9]:
np_a5.reshape(1, np_a5.shape[0] * np_a5.shape[1])

# both tries to convert multi-dimentional array to one dimentional array
np_a5.flatten()
np_a5.ravel()

array([1., 0., 2., 0.])

## Baisc array methods

In [10]:
np.arange(1, 6, 2) # (from, to, skip?=1)

array([1, 3, 5])

In [11]:
np.linspace(1, 10, 5) # even difference between no's (from, to, generate_count)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [12]:
np.logspace(1, 10, 3) # even logrithmic difference between no's

array([1.00000000e+01, 3.16227766e+05, 1.00000000e+10])

In [13]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.zeros([2, 2, 3]) # (dimentions, rows , columns)

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.tile([3, 4], 2)

array([3, 4, 3, 4])

In [17]:
np.repeat([3, 4], 2)

array([3, 3, 4, 4])

In [18]:
np.random.rand(2, 3) # (rows, columns)

array([[0.16376617, 0.97558264, 0.77688137],
       [0.02501447, 0.58228355, 0.52220467]])

In [19]:
np.random.randint(1, 100, [2, 3]) # (from, to, [rows, columns])

array([[96, 88, 83],
       [58, 17, 14]])

In [20]:
# fix the random results
np.random.seed(1)
np.random.randint(1, 100, [2, 3])

array([[38, 13, 73],
       [10, 76,  6]])

In [21]:
np.unique(np_a5)

array([0., 1., 2.])

In [22]:
np.unique(np_a5, return_counts=True)

(array([0., 1., 2.]), array([2, 1, 1], dtype=int64))

## Where

In [23]:
np_a7 = np.array([1, 2, 10, 11, 12])

index = np.where(np_a7>10)
np_a7[index]

array([11, 12])

In [24]:
np_a7[np_a7>10]

array([11, 12])

In [25]:
np_a7.argmax() # index of np_a7.max()

4

In [26]:
np_a7.argmin() # index of np_a7.min()

0

## File Handling

In [27]:
# np.savetext(file.csv, array, delimiter=',')
# np.savetext(file.csv, delimiter=',')

# save as bytes 
# np.save(file.npy, array)
# np.load(file.npy)

# save multiple arrays
# np.savez(file.npy, array1, array2)
# np.loadz(file.npy).files

## Concatination and sorting

In [28]:
# for concatination arrays must be of same order
arr_1 = np.array([1, 2 , 3, 4])
arr_2 = np.array([5, 6, 7, 8])

# np.hstack([arr_1, arr_2])
np.concatenate([arr_1, arr_2], axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
arr_1 = np.random.randint(1, 100, [2, 2])
arr_2 = np.random.randint(1, 100, [2, 2])

# np.vstack([arr_1, arr_2])
np.concatenate([arr_1, arr_2], axis=1)

array([[80, 65, 77, 72],
       [17,  2,  7, 26]])

## working with dates

In [30]:
date = np.datetime64('2021-10-23 23:40:30')

date

numpy.datetime64('2021-10-23T23:40:30')

In [31]:
date + 10

numpy.datetime64('2021-10-23T23:40:40')

In [32]:
one_day = np.timedelta64(1, 'D')

date + one_day

numpy.datetime64('2021-10-24T23:40:30')

In [33]:
one_min = np.timedelta64(1, 'm')

date + one_min

numpy.datetime64('2021-10-23T23:41:30')